// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWebSocket(arg1, arg2) {
  return window['go']['main']['App']['ConnectWebSocket'](arg1, arg2);
}

export function DisconnectWebSocket(arg1) {
  return window['go']['main']['App']['DisconnectWebSocket'](arg1);
}

export function SendWebSocketBinary(arg1, arg2) {
  return window['go']['main']['App']['SendWebSocketBinary'](arg1, arg2);
}

export function SendWebSocketMessage(arg1, arg2) {
  return window['go']['main']['App']['SendWebSocketMessage'](arg1, arg2);
}
