// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWebSocket(arg1:string,arg2:string):Promise<string>;

export function DisconnectWebSocket(arg1:string):Promise<void>;

export function SendWebSocketBinary(arg1:string,arg2:string):Promise<void>;

export function SendWebSocketMessage(arg1:string,arg2:string):Promise<void>;
